Repository facebookresearch/fairchem, pull requests merged in 2024-10, with the labels that each got.

#831 Add tests for hydra gemnet OC scaling factor generation and loading; Raise error on fail to load scaling factors
  docs/legacy_tutorials/OCP_Tutorial.md
  src/fairchem/core/modules/scaling/compat.py
  src/fairchem/core/modules/scaling/fit.py
  tests/core/e2e/test_s2ef.py
Labels: bug, patch

#873 Add singleton logger
  src/fairchem/core/common/logger.py
  src/fairchem/core/trainers/base_trainer.py
Labels: enhancement, minor

#867 Add hydra entrypoint
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/_cli.py
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/distutils.py
  src/fairchem/core/common/flags.py
  src/fairchem/core/common/relaxation/optimizers/lbfgs_torch.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/components/runner.py
  tests/core/test_hydra_cli.py
  tests/core/test_hydra_cli.yml
Labels: enhancement, minor

#875 Add script to make release from fine tuned hydra
  src/fairchem/core/scripts/convert_hydra_to_release.py
  tests/core/e2e/test_e2e_commons.py
  tests/core/e2e/test_e2e_finetune_hydra.py
  tests/core/models/test_configs/test_finetune_hydra.yml
Labels: enhancement, patch

#882 adding tutorial
  src/fairchem/applications/cattsunami/tutorial/adding_a_rxn_to_the_db.ipynb
Labels: documentation, minor

#884 remove destroy_process_group() from finally wrapper as it can hang
  src/fairchem/core/common/utils.py
  tests/core/e2e/test_s2ef.py
Labels: bug, patch

#874 Read the logger logging level from environment variable
  src/fairchem/core/common/utils.py
Labels: enhancement, patch

#891 add per adsorbate download links
  docs/core/datasets/oc20.md
Labels: documentation, patch

#856 Make eqv2 old to hydra converter work with old old configs :'(
  src/fairchem/core/models/equiformer_v2/eqv2_to_eqv2_hydra.py
Labels: enhancement, patch

#898 add hydra freeze backbone option
  src/fairchem/core/models/base.py
  tests/core/e2e/test_e2e_finetune_hydra.py
Labels: enhancement, minor

#896 Updated loss and eval metrics
  src/fairchem/core/common/registry.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/modules/evaluator.py
  src/fairchem/core/modules/loss.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/e2e/test_s2efs.py
  tests/core/modules/test_loss.py
Labels: enhancement, minor
