Repository facebookresearch/fairchem, pull requests merged in 2024-11, with the labels that each got.

#881 add omat24 docs
  configs/omat24/all/eqV2_153M.yml
  configs/omat24/all/eqV2_31M.yml
  configs/omat24/all/eqV2_86M.yml
  configs/omat24/finetune/eqV2_153M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_31M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_86M_ft_salexmptrj.yml
  configs/omat24/mptrj/eqV2_153M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_mptrj.yml
  configs/omat24/mptrj/eqV2_86M_dens_mptrj.yml
  configs/omat24/mptrj_dataset.yml
  configs/omat24/mptrj_salex_dataset.yaml
  configs/omat24/omat24_dataset.yml
  docs/_toc.yml
  docs/core/datasets/omat24.md
  docs/core/model_checkpoints.md
  docs/index.md
Labels: documentation, minor

#903 Rename hydra heads
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  src/fairchem/core/models/equiformer_v2/heads/__init__.py
  src/fairchem/core/models/equiformer_v2/heads/rank2.py
  src/fairchem/core/models/equiformer_v2/heads/scalar.py
  src/fairchem/core/models/equiformer_v2/heads/vector.py
  src/fairchem/core/models/equiformer_v2/prediction_heads/__init__.py
  src/fairchem/core/models/equiformer_v2/weight_initialization.py
  tests/core/models/test_rank2_head.py
Labels: enhancement, minor

#908 Omat24 doc fix
  docs/core/datasets/omat24.md
  docs/core/model_checkpoints.md
Labels: documentation, patch

#904 Sort paths in datasets
  src/fairchem/core/datasets/base_dataset.py
Labels: bug, patch

#907 Add utils for logging weight tables and tensor stats
  src/fairchem/core/common/logger.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/trainers/base_trainer.py
Labels: enhancement, patch

#915 OCx24 Release
  docs/_toc.yml
  docs/core/datasets/ocx24.md
  packages/fairchem-applications-ocx/pyproject.toml
  packages/fairchem-applications-ocx/src
  src/fairchem/applications/ocx/README.md
  src/fairchem/applications/ocx/__init__.py
  src/fairchem/applications/ocx/analysis/README.md
  src/fairchem/applications/ocx/analysis/ml_inference.py
  src/fairchem/applications/ocx/analysis/ml_train.py
  src/fairchem/applications/ocx/co2rr_summary_figure.png
  src/fairchem/applications/ocx/core/__init__.py
  src/fairchem/applications/ocx/core/data_handling.py
  src/fairchem/applications/ocx/core/features.py
  src/fairchem/applications/ocx/core/voltage.py
  src/fairchem/applications/ocx/core/wulff.py
  src/fairchem/applications/ocx/data/README.md
  src/fairchem/applications/ocx/data/computational_data/README.md
  src/fairchem/applications/ocx/data/computational_data/cod_matches_lookup.pkl
  src/fairchem/applications/ocx/data/computational_data/her_candidates.csv
  src/fairchem/applications/ocx/data/experimental_data/ExpDataDump_241113.csv
  src/fairchem/applications/ocx/data/experimental_data/ExpDataDump_241113_clean.csv
  src/fairchem/applications/ocx/data/experimental_data/README.md
  src/fairchem/applications/ocx/data/experimental_data/XRDDataDump-241113.csv
  src/fairchem/applications/ocx/data/experimental_data/XRFDataDump-241113.csv
  src/fairchem/applications/ocx/data/experimental_data/supporting_data/batches_info.csv
  src/fairchem/applications/ocx/data/experimental_data/supporting_data/materials_id-241113.csv
  src/fairchem/applications/ocx/data/experimental_data/supporting_data/materials_postprocessing_id-241113.csv
  src/fairchem/applications/ocx/data/experimental_data/supporting_data/vsp_synthesis_params.csv
  src/fairchem/applications/ocx/data/processed_data/CO2R_40_70_all.csv
  src/fairchem/applications/ocx/data/processed_data/CO2R_40_70_matched.csv
  src/fairchem/applications/ocx/data/processed_data/HER_40_70_all.csv
  src/fairchem/applications/ocx/data/processed_data/HER_40_70_matched.csv
  src/fairchem/applications/ocx/data/processed_data/README.md
Labels: enhancement, minor

#912 Create a issue template for bugs
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/misc.yaml
Labels: enhancement, patch

#920 replication use .item(); fix hydra_cli
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
  tests/core/test_hydra_cli.yml
Labels: enhancement, minor

#916 add ema to BaseTrainer init
  src/fairchem/core/trainers/base_trainer.py
Labels: bug, patch

#917 remove duplicate header in fairchem-data-om/pyproject.toml
  packages/fairchem-data-om/pyproject.toml
Labels: enhancement, minor

#893 Update ODAC model checkpoints
  docs/core/model_checkpoints.md
Labels: documentation, stale, minor

#927 update omat24 configs for new loss
  configs/omat24/all/eqV2_153M.yml
  configs/omat24/all/eqV2_31M.yml
  configs/omat24/all/eqV2_86M.yml
  configs/omat24/finetune/eqV2_153M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_31M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_86M_ft_salexmptrj.yml
  configs/omat24/mptrj/eqV2_153M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_mptrj.yml
  configs/omat24/mptrj/eqV2_86M_dens_mptrj.yml
Labels: documentation, patch

#894 Add wandb logger init to hydra runners
  src/fairchem/core/_cli_hydra.py
Labels: enhancement, minor
