Repository facebookresearch/fairchem, pull requests merged in 2024-08, with the labels that each got.

#801 Automated semantic versioning and release drafter
  .github/release-drafter-core.yml
  .github/release-drafter-data_oc.yml
  .github/release-drafter-demo_ocpapi.yml
  .github/release-drafter_applications_cattsunami.yml
  .github/workflows/label_checker.yml
  .github/workflows/release-drafter-applications_cattsunami.yml
  .github/workflows/release-drafter-core.yml
  .github/workflows/release-drafter-data_oc.yml
  .github/workflows/release-drafter-demo_ocpapi.yml
  .github/workflows/release.yml
  .github/workflows/test-release.yml
Labels: enhancement, minor

#805 typo in filename for release-draft config for cattsunami
  .github/release-drafter-applications_cattsunami.yml
Labels: bug, patch

#807 #806: Move data.db to s3 and download via download_large_files
  docs/core/inference.md
  src/fairchem/core/scripts/download_large_files.py
Labels: bug, documentation, patch

#803 Fix job resume on non-preemption type failures
  src/fairchem/core/_cli.py
  src/fairchem/core/common/slurm.py
  src/fairchem/core/tasks/task.py
  src/fairchem/core/trainers/base_trainer.py
Labels: bug, patch

#797 Finetune Hydra
  src/fairchem/core/common/utils.py
  src/fairchem/core/models/base.py
  src/fairchem/core/models/finetune_hydra.py
  src/fairchem/core/trainers/base_trainer.py
  tests/core/datasets/test_create_dataset.py
  tests/core/e2e/test_e2e_commons.py
  tests/core/e2e/test_e2e_finetune_hydra.py
  tests/core/e2e/test_s2ef.py
  tests/core/models/test_configs/test_finetune_hydra.yml
Labels: enhancement, minor

#804 add resolution flag to escn
  src/fairchem/core/models/escn/escn.py
  src/fairchem/core/models/escn/so3.py
Labels: enhancement, patch

#811 Activation checkpoint equiformersv2
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  tests/core/models/test_equiformer_v2.py
Labels: enhancement, minor

#813 load linref and normalizer on cuda device when resuming from checkpoint
  src/fairchem/core/trainers/base_trainer.py
Labels: bug, patch

#799 add example hydra config
  configs/ocp_hydra_example.yml
Labels: documentation

#809 Explicitly initialize weights even if initialization method is "uniform"
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  tests/core/models/__snapshots__/test_equiformer_v2.ambr
Labels: enhancement, patch

#792 Rank2 tensor head
  src/fairchem/core/models/base.py
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  src/fairchem/core/models/equiformer_v2/prediction_heads/__init__.py
  src/fairchem/core/models/equiformer_v2/prediction_heads/rank2.py
  src/fairchem/core/models/escn/escn.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/conftest.py
  tests/core/e2e/conftest.py
  tests/core/e2e/test_e2e_commons.py
  tests/core/e2e/test_s2ef.py
  tests/core/e2e/test_s2efs.py
  tests/core/models/__snapshots__/test_equiformer_v2.ambr
  tests/core/models/test_configs/test_equiformerv2_hydra.yml
  tests/core/models/test_rank2_head.py
  tests/core/modules/conftest.py
Labels: enhancement, minor

#814 Fuse all hydras
  configs/ocp_hydra_example.yml
  src/fairchem/core/common/utils.py
  src/fairchem/core/models/base.py
  src/fairchem/core/models/finetune_hydra.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/e2e/test_e2e_finetune_hydra.py
  tests/core/e2e/test_s2efs.py
  tests/core/models/test_configs/test_dpp_hydra.yml
  tests/core/models/test_configs/test_equiformerv2_hydra.yml
  tests/core/models/test_configs/test_escn_hydra.yml
  tests/core/models/test_configs/test_finetune_hydra.yml
  tests/core/models/test_configs/test_gemnet_dt_hydra.yml
  tests/core/models/test_configs/test_gemnet_dt_hydra_grad.yml
  tests/core/models/test_configs/test_gemnet_oc_hydra.yml
  tests/core/models/test_configs/test_gemnet_oc_hydra_grad.yml
  tests/core/models/test_configs/test_painn_hydra.yml
  tests/core/models/test_equiformer_v2.py
Labels: enhancement, minor

#752 FM-v4 branch into main
  src/fairchem/core/common/utils.py
  src/fairchem/core/datasets/_utils.py
  src/fairchem/core/modules/loss.py
  src/fairchem/core/modules/transforms.py
  src/fairchem/core/trainers/base_trainer.py
  tests/core/common/test_yaml_loader.py
Labels: enhancement, minor

#820 Use abs run_dir paths by default
  src/fairchem/core/common/flags.py
Labels: enhancement, patch

#817 Add check to max num atoms
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  src/fairchem/core/models/escn/escn.py
  tests/core/e2e/test_s2ef.py
Labels: enhancement, patch

#819 fix gemnet scaling factors fit.py and add a test
  src/fairchem/core/modules/scaling/fit.py
  tests/core/e2e/test_e2e_commons.py
  tests/core/e2e/test_s2ef.py
Labels: enhancement, patch

#818 add option to apply mean to energy
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
Labels: enhancement, patch
