Repository facebookresearch/fairchem, pull requests merged in 2024-12, with the labels that each got.

#718 OptimizableBatch and stress relaxations
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/common/relaxation/__init__.py
  src/fairchem/core/common/relaxation/ase_utils.py
  src/fairchem/core/common/relaxation/ml_relaxation.py
  src/fairchem/core/common/relaxation/optimizable.py
  src/fairchem/core/common/relaxation/optimizers/__init__.py
  src/fairchem/core/common/relaxation/optimizers/lbfgs_torch.py
  src/fairchem/core/datasets/ase_datasets.py
  src/fairchem/core/models/base.py
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/common/conftest.py
  tests/core/common/test_ase_calculator.py
  tests/core/common/test_lbfgs_torch.py
  tests/core/common/test_optimizable.py
  tests/core/datasets/test_ase_datasets.py
Labels: enhancement, minor

#928 pin pytorch at 2_4_0
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/fairchem-core/pyproject.toml
Labels: dependencies, patch

#931 Add cuda set_device for local run
  src/fairchem/core/common/distutils.py
Labels: bug, patch

#922 OCPCalculator output_only option
  src/fairchem/core/common/relaxation/ase_utils.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/common/__snapshots__/test_ase_calculator.ambr
  tests/core/common/test_ase_calculator.py
Labels: bug, minor

#935 set tensor dtypes and use torch.tensor to initialize tensors in a2g
  src/fairchem/core/preprocessing/atoms_to_graphs.py
Labels: bug, patch

#948 Filter based on additional metadata fields
  src/fairchem/core/datasets/base_dataset.py
  tests/core/common/test_data_parallel_batch_sampler.py
  tests/core/datasets/test_create_dataset.py
Labels: enhancement, patch

#949 add pypi version badge
  README.md
Labels: documentation, patch
