Repository facebookresearch/fairchem, pull requests merged in 2024-09, with the labels that each got.

#827 add run group
  src/fairchem/core/common/logger.py
Labels: enhancement, patch

#824 Load normalizers patch
  src/fairchem/core/modules/normalization/_load_utils.py
  src/fairchem/core/modules/normalization/normalizer.py
Labels: bug, patch

#828 Add mean e to escn energy head
  src/fairchem/core/models/escn/escn.py
Labels: enhancement, patch

#825 update to gemnet-oc hydra force head to work with amp
  src/fairchem/core/models/gemnet_oc/gemnet_oc.py
Labels: bug, patch

#829 add tags, fix min_ab slab
  src/fairchem/data/oc/core/interface_config.py
  src/fairchem/data/oc/core/slab.py
  src/fairchem/data/oc/utils/vasp.py
  src/fairchem/data/oc/utils/vasp_flags.py
Labels: bug, patch

#832 add docstring. Add support for different pseudopotential path
  src/fairchem/data/oc/core/slab.py
  src/fairchem/data/oc/utils/vasp.py
  src/fairchem/data/oc/utils/vasp_flags.py
Labels: enhancement, patch

#837 Sort dbs AseDBDataset
  src/fairchem/core/datasets/ase_datasets.py
Labels: bug, patch

#840 explicitly define ispin for oc20 bulks
  src/fairchem/data/oc/utils/vasp_flags.py
Labels: bug, patch

#826 Torch compile + export escn
  src/fairchem/core/common/test_utils.py
  src/fairchem/core/datasets/lmdb_dataset.py
  src/fairchem/core/models/escn/escn_exportable.py
  src/fairchem/core/models/escn/so3_exportable.py
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  tests/core/models/test_escn_compiles.py
Labels: enhancement, minor

#833 Delete distributed option - Always use DDP
  docs/core/fine-tuning/fine-tuning-oxides.md
  docs/core/inference.md
  docs/tutorials/advanced/fine-tuning-in-python.md
  src/fairchem/core/_cli.py
  src/fairchem/core/common/distutils.py
  src/fairchem/core/common/flags.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
  tests/core/e2e/test_e2e_commons.py
  tests/core/e2e/test_e2e_finetune_hydra.py
  tests/core/e2e/test_s2ef.py
  tests/core/e2e/test_s2efs.py
  tests/core/test_cli.py
Labels: enhancement, minor

#850 Add inference_only option to trainers
  src/fairchem/core/common/data_parallel.py
  src/fairchem/core/common/relaxation/ase_utils.py
  src/fairchem/core/models/equiformer_v2/equiformer_v2_deprecated.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
Labels: bug, minor, patch

#846 add script to port old equiv2 checkpoint+yaml to hydra version
  src/fairchem/core/models/equiformer_v2/eqv2_to_eqv2_hydra.py
  src/fairchem/core/scripts/eqv2_to_hydra_eqv2.py
  tests/core/e2e/test_s2ef.py
Labels: enhancement, patch

#841 Do not shadow built in `property`
  src/fairchem/core/trainers/ocp_trainer.py
Labels: enhancement, patch

#845 Bump torch2.4.1 and pyg
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/requirements-optional.txt
  packages/requirements.txt
  tests/core/models/test_escn_compiles.py
Labels: dependencies, minor

#857 bump torch in pyproject.toml
  packages/fairchem-applications-cattsunami/pyproject.toml
  packages/fairchem-core/pyproject.toml
Labels: dependencies, minor

#853 enable ruff formatter
  .github/workflows/lint.yml
  ruff.toml
  src/fairchem/core/_cli.py
  src/fairchem/core/common/distutils.py
  src/fairchem/core/common/logger.py
  src/fairchem/core/common/profiler_utils.py
  src/fairchem/core/common/slurm.py
  src/fairchem/core/common/test_utils.py
  src/fairchem/core/datasets/lmdb_dataset.py
  src/fairchem/core/models/base.py
  src/fairchem/core/models/dimenet_plus_plus.py
  src/fairchem/core/models/equiformer_v2/equiformer_v2.py
  src/fairchem/core/models/escn/escn.py
  src/fairchem/core/models/escn/escn_exportable.py
  src/fairchem/core/models/escn/so3.py
  src/fairchem/core/models/escn/so3_exportable.py
  src/fairchem/core/models/schnet.py
  src/fairchem/core/modules/scaling/fit.py
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  src/fairchem/core/tasks/task.py
Labels: enhancement, minor

#862 ocpapi dependencies / requests -> 2.32.3
  packages/fairchem-demo-ocpapi/pyproject.toml
Labels: dependencies

#848 ESCN export II
  src/fairchem/core/models/escn/escn_exportable.py
  src/fairchem/core/models/escn/so3_exportable.py
  tests/core/models/test_escn_compiles.py
Labels: enhancement, minor

#863 fix bug where trainer state not being loaded
  src/fairchem/core/common/relaxation/ase_utils.py
  src/fairchem/core/trainers/base_trainer.py
Labels: bug, patch

#864 add export link
  docs/core/model_checkpoints.md
Labels: enhancement, patch

#858 update CI tests to py 3.12
  .github/workflows/build.yml
  .github/workflows/build_docs.yml
  .github/workflows/integration-test.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/fairchem-core/pyproject.toml
  packages/fairchem-data-oc/pyproject.toml
  packages/requirements.txt
Labels: dependencies, minor

#859 change logic to catch missing outputs
  src/fairchem/core/trainers/ocp_trainer.py
Labels: enhancement, patch

#865 throw error when metadata is non integer
  src/fairchem/core/datasets/base_dataset.py
Labels: enhancement, patch

#866 Match escn_exportable with escn main
  src/fairchem/core/models/escn/escn_exportable.py
  src/fairchem/core/models/escn/so3.py
  src/fairchem/core/models/escn/so3_exportable.py
  tests/core/models/test_escn_compiles.py
Labels: bug, patch

#852 add act checkpointing to escn
  src/fairchem/core/models/escn/escn.py
  tests/core/e2e/test_s2ef.py
Labels: enhancement, patch
