Repository facebookresearch/fairchem, pull requests merged in 2025-06, with the labels that each got.

#1205 Fix ac mole bug
  src/fairchem/core/models/uma/escn_md_block.py
  src/fairchem/core/models/uma/nn/mole.py
  tests/core/units/mlip_unit/test_inference_modes.py
Labels: bug, minor, cla signed

#1181 Batch inference cleanup
  configs/uma/benchmark/mp-binary-pbe-elasticity.yaml
  src/fairchem/core/calculate/ase_calculator.py
  src/fairchem/core/calculate/pretrained_mlip.py
  src/fairchem/core/components/benchmark/uma_speed_benchmark.py
  src/fairchem/core/datasets/atomic_data.py
  src/fairchem/core/scripts/migrate_checkpoint.py
  src/fairchem/core/units/mlip_unit/__init__.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
  src/fairchem/core/units/mlip_unit/predict.py
  src/fairchem/core/units/mlip_unit/utils.py
  tests/conftest.py
  tests/core/calculate/test_ase_calculator.py
  tests/core/units/mlip_unit/test_aperiodic.py
  tests/core/units/mlip_unit/test_equivariance.py
  tests/core/units/mlip_unit/test_finetuning.py
  tests/core/units/mlip_unit/test_inference_checkpoint.py
  tests/core/units/mlip_unit/test_inference_modes.py
  tests/core/units/mlip_unit/test_predict.py
Labels: enhancement, patch, cla signed

#1223 Fix bug when taskname is enum instead of str
  src/fairchem/core/calculate/ase_calculator.py
  src/fairchem/core/models/uma/escn_moe.py
  tests/core/calculate/test_ase_calculator.py
Labels: bug, patch, cla signed

#1226 Add zenodo tag to README.md
  README.md
Labels: documentation, cla signed, no-op

#1232 Batch inference examples in docs
  CITATION.cff
  README.md
  docs/index.md
Labels: documentation, cla signed, no-op

#1239 fix setting implemented properties
  src/fairchem/core/calculate/ase_calculator.py
  tests/core/calculate/test_ase_calculator.py
Labels: bug, patch, cla signed

#1185 release isolated atom refs
  configs/uma/training_release/element_refs/iso_atom_elem_refs.yaml
  src/fairchem/core/calculate/ase_calculator.py
  src/fairchem/core/calculate/pretrained_mlip.py
  src/fairchem/core/calculate/pretrained_models.json
  src/fairchem/core/units/mlip_unit/__init__.py
  src/fairchem/core/units/mlip_unit/predict.py
  tests/core/calculate/test_ase_calculator.py
Labels: enhancement, patch, cla signed

#1256 add Be+ for OMol benchmarking
  configs/uma/training_release/element_refs/iso_atom_elem_refs.yaml
Labels: documentation, minor, cla signed

#1257 Add pr target
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: enhancement, github_actions, cla signed, no-op

#1258 add in model_version to mole and fix composition embebdding
  src/fairchem/core/models/uma/escn_moe.py
  src/fairchem/core/scripts/migrate_checkpoint.py
Labels: bug, minor, cla signed

#1243 add option to return checkpoint along with model
  src/fairchem/core/units/mlip_unit/utils.py
Labels: enhancement, patch, cla signed

#1276 Change everything to PR target
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: enhancement, github_actions, cla signed, no-op

#1281 Switch to pr target only
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: enhancement, github_actions, cla signed, no-op

#1283 Dont use tf32 on by default
  src/fairchem/core/units/mlip_unit/api/inference.py
Labels: enhancement, minor, cla signed

#1282 ODAC tutorial (#1279)
  docs/_toc.yml
  docs/dac/examples_tutorials/WOBHEB_flexible.png
  docs/dac/examples_tutorials/adsorption_energies.md
  docs/dac/examples_tutorials/adsorption_energy.md
  docs/dac/examples_tutorials/structures/OPAGIX.cif
  docs/dac/examples_tutorials/structures/OPAGIX_w_CO2.cif
  docs/dac/examples_tutorials/structures/WOBHEB_0.11.cif
  docs/dac/examples_tutorials/structures/WOBHEB_H2O.cif
  docs/dac/examples_tutorials/structures/co2.xyz
  docs/dac/examples_tutorials/summary.md
Labels: documentation, patch, cla signed

#1284 odac tutorial small fix
  docs/dac/examples_tutorials/adsorption_energy.md
Labels: documentation, patch, cla signed

#1286 Add osc -> omc migration for non ema checkpoint
  src/fairchem/core/scripts/migrate_checkpoint.py
Labels: bug, minor, cla signed

#1294 Add basis set
  src/fairchem/data/om/omdata/orca/def2-tzvpd.bas
Labels: documentation, minor, patch, cla signed

#1297 Switch back to PR
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: enhancement, dependencies, cla signed, no-op

#1289 Add UMA self-contained tutorial
  .github/workflows/build_docs.yml
  docs/_config.yml
  docs/_toc.yml
  docs/catalysts/datasets/oc20neb.md
  docs/catalysts/examples_tutorials/adsorption_energies/adsorption_energies.md
  docs/catalysts/examples_tutorials/cattsunami_tutorial.md
  docs/dac/examples_tutorials/adsorption_energy.md
  docs/uma_tutorials/summary.md
  docs/uma_tutorials/uma_tutorial.md
Labels: documentation, patch, cla signed

#1313 More small doc fixes
  docs/_config.yml
  docs/_toc.yml
  docs/catalysts/examples_tutorials/OCP-introduction.md
  docs/catalysts/examples_tutorials/adsorbml_walkthrough.md
  docs/catalysts/examples_tutorials/adsorption_energies/adsorption_energies.md
  docs/catalysts/examples_tutorials/cattsunami_tutorial.md
  docs/catalysts/examples_tutorials/ocpapi.md
  docs/core/common_tasks/ase_calculator.md
  docs/core/common_tasks/batch_inference.md
  docs/core/quickstart.md
  docs/core/simplified_install.md
  docs/dac/examples_tutorials/adsorption_energy.md
  docs/index.md
  docs/inorganic_materials/examples_tutorials/bulk_stability.md
  docs/inorganic_materials/examples_tutorials/elastic.md
  docs/inorganic_materials/examples_tutorials/phonons.md
Labels: documentation, patch, cla signed

#1315 Fix docs toc
  docs/_toc.yml
  docs/catalysts/examples_tutorials/OCP-introduction.md
  docs/catalysts/examples_tutorials/adsorbml_walkthrough.md
  docs/catalysts/examples_tutorials/adsorption_energies/adsorption_energies.md
  docs/catalysts/examples_tutorials/cattsunami_tutorial.md
  docs/catalysts/examples_tutorials/ocpapi.md
  docs/core/common_tasks/ase_calculator.md
  docs/core/common_tasks/batch_inference.md
  docs/core/quickstart.md
  docs/dac/examples_tutorials/adsorption_energy.md
  docs/index.md
  docs/inorganic_materials/examples_tutorials/bulk_stability.md
  docs/inorganic_materials/examples_tutorials/elastic.md
  docs/inorganic_materials/examples_tutorials/phonons.md
Labels: documentation, patch, cla signed
