Repository facebookresearch/fairchem, pull requests merged in 2025-05, with the labels that each got.

#1141 Update README.md
  README.md
Labels: documentation, minor, cla signed

#1144 Update README.md
  README.md
Labels: cla signed

#1150 Clean out ESEN/schnet that was suppose be deleted in the merge
  README.md
  src/fairchem/core/models/esen/Jd.pt
  src/fairchem/core/models/esen/__init__.py
  src/fairchem/core/models/esen/common/__init__.py
  src/fairchem/core/models/esen/common/rotation.py
  src/fairchem/core/models/esen/common/so3.py
  src/fairchem/core/models/esen/esen.py
  src/fairchem/core/models/esen/esen_block.py
  src/fairchem/core/models/esen/esen_dens.py
  src/fairchem/core/models/esen/nn/__init__.py
  src/fairchem/core/models/esen/nn/activation.py
  src/fairchem/core/models/esen/nn/embedding.py
  src/fairchem/core/models/esen/nn/layer_norm.py
  src/fairchem/core/models/esen/nn/radial.py
  src/fairchem/core/models/esen/nn/rank2.py
  src/fairchem/core/models/esen/nn/so2_layers.py
  src/fairchem/core/models/esen/nn/so3_layers.py
  src/fairchem/core/models/esen/trainers/__init__.py
  src/fairchem/core/models/esen/trainers/lr_scheduler.py
  src/fairchem/core/models/esen/trainers/trainer.py
  src/fairchem/core/models/schnet.py
Labels: documentation, patch, cla signed, no-op

#1149 update PR label checking
  .github/release-drafter-applications_cattsunami.yml
  .github/release-drafter-core.yml
  .github/release-drafter-data_oc.yml
  .github/release-drafter-demo_ocpapi.yml
  .github/workflows/label_checker.yml
Labels: test, cla signed, no-op

#1151 move plotting to training only so calculator doesnt use it
  src/fairchem/core/models/uma/escn_moe.py
  src/fairchem/core/models/uma/nn/mole_utils.py
Labels: enhancement, patch, cla signed

#1154 Remove a few compile tests
  .github/workflows/build_docs.yml
  tests/core/common/test_calculator.py
  tests/core/models/uma/test_compile.py
Labels: enhancement, patch, cla signed

#1145 Breakup common utils
  src/fairchem/core/common/utils.py
  src/fairchem/core/datasets/lmdb_dataset.py
  src/fairchem/core/datasets/oc22_lmdb_dataset.py
  src/fairchem/core/graph/compute.py
  src/fairchem/core/graph/radius_graph_pbc.py
  src/fairchem/core/models/esen/nn/rank2.py
  src/fairchem/core/models/uma/escn_md.py
  src/fairchem/core/models/utils/irreps.py
  src/fairchem/core/modules/normalization/_load_utils.py
  src/fairchem/core/modules/scaling/fit.py
  src/fairchem/core/modules/scheduler.py
  src/fairchem/core/modules/transforms.py
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  src/fairchem/core/scripts/fit_normalizers.py
  src/fairchem/core/scripts/fit_references.py
  src/fairchem/core/scripts/hpo/README.md
  src/fairchem/core/scripts/hpo/run_tune.py
  src/fairchem/core/scripts/hpo/run_tune_pbt.py
  src/fairchem/core/scripts/hpo/slurm/start-head.sh
  src/fairchem/core/scripts/hpo/slurm/start-worker.sh
  src/fairchem/core/scripts/hpo/slurm/submit-ray-cluster.sbatch
  tests/core/common/test_yaml_loader.py
  tests/core/preprocessing/test_pbc.py
  tests/core/preprocessing/test_radius_graph_pbc.py
Labels: patch, cla signed, refactor, no-op

#1164 v2 logo
  README.md
Labels: cla signed, no-op

#1159 No test on merge queue
  .github/workflows/label_checker.yml
  .github/workflows/test.yml
Labels: test, cla signed, no-op

#1169 remove lin_ref
  src/fairchem/core/datasets/ase_datasets.py
  src/fairchem/core/datasets/base_dataset.py
Labels: enhancement, cla signed, no-op

#1170 fix merge for non mole
  src/fairchem/core/models/uma/escn_moe.py
  tests/core/units/mlip_unit/test_inference_modes.py
Labels: bug, cla signed, no-op

#1173 update readme and cleanup warnings
  README.md
  src/fairchem/core/models/uma/escn_moe.py
Labels: documentation, no-op

#1174 update README
  README.md
  src/fairchem/core/README.md
Labels: documentation, cla signed, no-op

#1160 Fairchemv2 docs update
  .github/workflows/build_docs.yml
  docs/_config.yml
  docs/_toc.yml
  docs/core/common_tasks/embeddings/embedding_monkeypatch.py
  docs/core/common_tasks/embeddings/embeddings.md
  docs/core/common_tasks/fine-tuning/fine-tuning.md
  docs/core/common_tasks/fine-tuning/oxides.db
  docs/core/common_tasks/fine-tuning/supporting-information.json
  docs/core/common_tasks/inference.md
  docs/core/common_tasks/training.md
  docs/core/datasets_models.md
  docs/core/install.md
  docs/core/intro.md
  docs/core/model_faq.md
  docs/core/quickstart.md
  docs/index.md
  packages/fairchem-applications-cattsunami/pyproject.toml
  src/fairchem/core/README.md
  src/fairchem/core/TRAIN.md
Labels: documentation, patch, cla signed

#1179 Update README.md
  README.md
Labels: documentation, cla signed, no-op

#1172 Enable local runs
  configs/uma/training_release/README.md
  configs/uma/training_release/dataset/uma_debug.yaml
  src/fairchem/core/_cli.py
Labels: enhancement, patch, cla signed

#1203 FAIRChem calculator `from_model_checkpoint` classmethod
  src/fairchem/core/calculate/ase_calculator.py
  tests/core/calculate/test_ase_calculator.py
Labels: enhancement, minor, cla signed

#1199 version uma
  README.md
  docs/core/quickstart.md
  src/fairchem/core/calculate/pretrained_mlip.py
  src/fairchem/core/calculate/pretrained_models.json
  tests/core/calculate/test_ase_calculator.py
Labels: documentation, cla signed, no-op

#1106 tile solvents
  src/fairchem/data/oc/core/adsorbate_slab_config.py
  src/fairchem/data/oc/core/interface_config.py
  src/fairchem/data/oc/databases/pkls/ions.pkl
  src/fairchem/data/oc/utils/vasp_flags.py
  tests/data/oc/tests/test_interface_config.py
Labels: enhancement, patch, cla signed
