Repository facebookresearch/fairchem, pull requests merged in 2025-07, with the labels that each got.

#1248 UMA Finetune scripts and docs
  configs/uma/finetune/data/uma_conserving_data_task_energy.yaml
  configs/uma/finetune/data/uma_conserving_data_task_energy_force.yaml
  configs/uma/finetune/data/uma_conserving_data_task_energy_force_stress.yaml
  configs/uma/finetune/uma_sm_finetune_template.yaml
  docs/core/common_tasks/fine_tuning.md
  docs/core/common_tasks/finetune_assets/train/structure_0001.traj
  docs/core/common_tasks/finetune_assets/train/structure_0002.traj
  docs/core/common_tasks/finetune_assets/val/structure_0000.traj
  docs/core/common_tasks/finetune_assets/val/structure_0004.traj
  docs/core/install.md
  src/fairchem/core/calculate/pretrained_mlip.py
  src/fairchem/core/datasets/base_dataset.py
  src/fairchem/core/scripts/create_finetune_dataset.py
  src/fairchem/core/scripts/create_uma_finetune_dataset.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
  tests/core/scripts/test_create_finetune_dataset.py
  tests/requirements.txt
Labels: enhancement, minor, cla signed

#1254 update FAIRChemCalculator initialization in benchmark configs
  configs/uma/benchmark/adsorbml.yaml
  configs/uma/benchmark/checkpoint/uma_lg.yaml
  configs/uma/benchmark/checkpoint/uma_md.yaml
  configs/uma/benchmark/checkpoint/uma_sm.yaml
  configs/uma/benchmark/checkpoint/uma_sm_omc.yaml
  configs/uma/benchmark/hea-is2re.yaml
  configs/uma/benchmark/kappa103.yaml
  configs/uma/benchmark/matbench-discovery-discovery.yaml
  configs/uma/benchmark/mdr-phonon.yaml
  configs/uma/benchmark/mp-binary-pbe-elasticity.yaml
  configs/uma/benchmark/mp-pbe-elasticity.yaml
  configs/uma/benchmark/nvemd-materials.yaml
  configs/uma/benchmark/nvemd-molecules.yaml
  configs/uma/benchmark/oc20-is2re-adsorption.yaml
  configs/uma/benchmark/oc20-s2ef-id.yaml
  configs/uma/benchmark/oc20-s2ef-ood-both.yaml
  configs/uma/benchmark/odac-s2ef-id.yaml
  configs/uma/benchmark/odac-s2ef-ood.yaml
  configs/uma/benchmark/omc-is2re-polymorphs.yaml
  configs/uma/benchmark/omc-is2re.yaml
  configs/uma/evaluate/checkpoint/uma_lg.yaml
  configs/uma/evaluate/checkpoint/uma_md.yaml
  configs/uma/evaluate/checkpoint/uma_sm.yaml
  configs/uma/evaluate/checkpoint/uma_sm_omc.yaml
  configs/uma/evaluate/cluster/h100_local.yaml
  configs/uma/evaluate/omc_conserving.yaml
  configs/uma/evaluate/omol_conserving.yaml
  configs/uma/evaluate/uma_conserving.yaml
  configs/uma/evaluate/uma_direct.yaml
  configs/uma/training_release/element_refs/uma_v1_hof_lin_refs.yaml
  src/fairchem/core/components/calculate/recipes/relax.py
  src/fairchem/core/components/calculate/relaxation_runner.py
Labels: documentation, cla signed, no-op

#1321 UMA 1.1 checkpoint release
  src/fairchem/core/calculate/pretrained_models.json
  tests/core/calculate/test_ase_calculator.py
Labels: enhancement, minor, cla signed

#1325 Update docs to use 1p1
  README.md
  docs/catalysts/datasets/oc20neb.md
  docs/catalysts/examples_tutorials/OCP-introduction.md
  docs/catalysts/examples_tutorials/adsorbml_walkthrough.md
  docs/catalysts/examples_tutorials/adsorption_energies/adsorption_energies.md
  docs/catalysts/examples_tutorials/cattsunami_tutorial.md
  docs/core/common_tasks/ase_calculator.md
  docs/core/common_tasks/batch_inference.md
  docs/core/common_tasks/workflows.md
  docs/core/quickstart.md
  docs/core/uma.md
  docs/dac/examples_tutorials/adsorption_energy.md
  docs/inorganic_materials/examples_tutorials/bulk_stability.md
  docs/inorganic_materials/examples_tutorials/elastic.md
  docs/inorganic_materials/examples_tutorials/phonons.md
Labels: documentation, cla signed, no-op

#1326 Add EScAIP Model
  configs/escaip/training/backbone/H1024L8.yaml
  configs/escaip/training/backbone/H1536L10.yaml
  configs/escaip/training/backbone/H512L10.yaml
  configs/escaip/training/backbone/H512L6.yaml
  configs/escaip/training/backbone/H640L10.yaml
  configs/escaip/training/cluster/fair_cluster.yaml
  configs/escaip/training/cluster/fair_local.yaml
  configs/escaip/training/dataset/fair_cluster_mptrj.yaml
  configs/escaip/training/dataset/fair_cluster_oc20.yaml
  configs/escaip/training/dataset/fair_cluster_spice.yaml
  configs/escaip/training/element_refs/mptrj_lin_refs.yaml
  configs/escaip/training/element_refs/spice_lin_refs.yaml
  configs/escaip/training/element_refs/uma_v1_hof_lin_refs.yaml
  configs/escaip/training/mptrj_direct_escaip_fair.yml
  configs/escaip/training/mptrj_finetune_escaip_fair.yml
  configs/escaip/training/oc20_direct_escaip_fair.yml
  configs/escaip/training/oc20_direct_escaip_fair_sm.yml
  configs/escaip/training/spice_grad_escaip_fair.yml
  configs/escaip/training/tasks/mptrj_direct.yaml
  configs/escaip/training/tasks/mptrj_grad.yaml
  configs/escaip/training/tasks/oc20_direct.yaml
  configs/escaip/training/tasks/spice_direct.yaml
  configs/escaip/training/tasks/spice_grad.yaml
  src/fairchem/core/_cli.py
  src/fairchem/core/models/escaip/EScAIP.py
  src/fairchem/core/models/escaip/__init__.py
  src/fairchem/core/models/escaip/configs.py
  src/fairchem/core/models/escaip/custom_types.py
  src/fairchem/core/models/escaip/modules/__init__.py
  src/fairchem/core/models/escaip/modules/base_block.py
  src/fairchem/core/models/escaip/modules/graph_attention_block.py
  src/fairchem/core/models/escaip/modules/input_block.py
  src/fairchem/core/models/escaip/modules/output_block.py
  src/fairchem/core/models/escaip/modules/readout_block.py
  src/fairchem/core/models/escaip/utils/data_preprocess.py
  src/fairchem/core/models/escaip/utils/graph_utils.py
  src/fairchem/core/models/escaip/utils/nn_utils.py
  src/fairchem/core/models/escaip/utils/radius_graph.py
  src/fairchem/core/models/escaip/utils/smearing.py
  src/fairchem/core/models/escaip/utils/stochastic_depth.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
  src/fairchem/core/units/mlip_unit/utils.py
  tests/core/models/escaip/test_forward.py
Labels: enhancement, minor, cla signed

#1314 if-condition requires `pbc is None`, but below we index pbc (#1309)
  src/fairchem/core/graph/radius_graph_pbc.py
Labels: bug, patch, cla signed

#1345 upgrading clusterscope
  packages/fairchem-core/pyproject.toml
Labels: bug, dependencies, patch, cla signed

#1310 Fix a bug in AtomicData.to_ase_single
  src/fairchem/core/datasets/atomic_data.py
  tests/core/datasets/test_atomic_data.py
Labels: bug, patch, cla signed

#1351 revert lmdb version
  packages/fairchem-core/pyproject.toml
  tests/requirements.txt
Labels: bug, dependencies, patch, cla signed

#1346 Fix a bug in AtomicData.to_ase_single (#1310)
  src/fairchem/core/datasets/atomic_data.py
  tests/core/datasets/test_atomic_data.py
Labels: bug, patch, cla signed

#1347 fix: correct expected value in external_graph_gen error message (True…
  src/fairchem/core/calculate/ase_calculator.py
Labels: bug, patch, cla signed

#1353 Trigger tests and build_docs on contributor check
  .github/actions/multi-trigger-cleanup/action.yml
  .github/actions/multi-trigger-setup/action.yml
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: enhancement, github_actions, patch, cla signed

#1376 bump clusterscope
  packages/fairchem-core/pyproject.toml
Labels: enhancement, minor, cla signed

#1381 ncore=4
  src/fairchem/data/oc/utils/vasp_flags.py
Labels: enhancement, patch
