Repository facebookresearch/fairchem, pull requests merged in 2025-08, with the labels that each got.

#1394 ODAC25 release
  docs/dac/datasets/odac23.md
  docs/dac/datasets/odac25.md
  docs/dac/models.md
Labels: enhancement, minor, cla signed

#1396 OMC25 dataset release docs update
  docs/core/common_tasks/ase_dataset_creation.md
  docs/core/uma.md
  docs/molecules/datasets/omc25.md
  docs/molecules/models.md
Labels: documentation, enhancement, minor, cla signed

#1399 Allow test and build_docs workflows to run on workflow_call
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: bug, github_actions, patch, cla signed

#1367 support eval restarts
  src/fairchem/core/components/calculate/adsorbml_runner.py
  src/fairchem/core/components/calculate/adsorption_runner.py
  src/fairchem/core/components/calculate/adsorption_singlepoint_runner.py
  src/fairchem/core/components/calculate/calculate_runner.py
  src/fairchem/core/components/calculate/elasticity_runner.py
  src/fairchem/core/components/calculate/kappa_runner.py
  src/fairchem/core/components/calculate/nve_md_runner.py
  src/fairchem/core/components/calculate/pairwise_ct_runner.py
  src/fairchem/core/components/calculate/phonon_runner.py
  src/fairchem/core/components/calculate/relaxation_runner.py
  src/fairchem/core/components/calculate/singlepoint_runner.py
Labels: enhancement, patch, cla signed

#1404 fix fp64 tests
  tests/core/units/mlip_unit/test_equivariance.py
Labels: enhancement, cla signed, no-op

#1407 update ensembles
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
  configs/uma/evaluate/element_refs/uma_hof_lin_refs.yaml
  configs/uma/evaluate/element_refs/uma_v1_hof_lin_refs.yaml
  configs/uma/evaluate/omc_conserving.yaml
  configs/uma/evaluate/omol_conserving.yaml
  configs/uma/evaluate/tasks/omc_conserving.yaml
  configs/uma/evaluate/tasks/omol_conserving.yaml
  configs/uma/evaluate/tasks/uma_conserving.yaml
  configs/uma/evaluate/tasks/uma_direct.yaml
  configs/uma/evaluate/uma_conserving.yaml
  configs/uma/evaluate/uma_direct.yaml
  docs/core/common_tasks/ase_dataset_creation.md
  docs/core/uma.md
  docs/dac/datasets/odac23.md
  docs/dac/datasets/odac25.md
  docs/dac/models.md
  docs/molecules/datasets/omc25.md
  docs/molecules/models.md
  packages/fairchem-data-omc/pyproject.toml
  packages/fairchem-data-omc/src
  src/fairchem/core/components/calculate/adsorbml_runner.py
  src/fairchem/core/components/calculate/adsorption_runner.py
  src/fairchem/core/components/calculate/adsorption_singlepoint_runner.py
  src/fairchem/core/components/calculate/calculate_runner.py
  src/fairchem/core/components/calculate/elasticity_runner.py
  src/fairchem/core/components/calculate/kappa_runner.py
  src/fairchem/core/components/calculate/nve_md_runner.py
  src/fairchem/core/components/calculate/pairwise_ct_runner.py
  src/fairchem/core/components/calculate/phonon_runner.py
  src/fairchem/core/components/calculate/relaxation_runner.py
  src/fairchem/core/components/calculate/singlepoint_runner.py
  src/fairchem/core/units/mlip_unit/utils.py
  src/fairchem/data/omc/LICENSE.md
  src/fairchem/data/omc/README.md
  src/fairchem/data/omc/__init__.py
  src/fairchem/data/omc/scripts/create_vasp_inputs.py
  src/fairchem/data/omc/scripts/incars/incar_relax.yml
  src/fairchem/data/omc/scripts/incars/incar_relax_light.yml
  src/fairchem/data/omc/scripts/incars/incar_static.yml
  tests/core/units/mlip_unit/test_equivariance.py
Labels: cla signed

#1411 Add inference-only tasks to allow predicting on tasks not trained on
  configs/uma/finetune/data/uma_conserving_data_task_energy.yaml
  configs/uma/finetune/data/uma_conserving_data_task_energy_force.yaml
  configs/uma/finetune/data/uma_conserving_data_task_energy_force_stress.yaml
  src/fairchem/core/datasets/collaters/mt_collater.py
  src/fairchem/core/scripts/create_uma_finetune_dataset.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
  tests/core/scripts/test_create_finetune_dataset.py
Labels: enhancement, minor, cla signed

#1397 enable updating the edges of an AtomicData batch
  src/fairchem/core/datasets/atomic_data.py
  tests/core/datasets/test_atomic_data.py
Labels: enhancement, patch, cla signed

#1421 [ BE ] add user accessible embeddings
  src/fairchem/core/models/uma/escn_md.py
  tests/core/units/mlip_unit/test_emeddings.py
Labels: enhancement, minor, cla signed

#1410 [BE] Re-enable codecov
  .github/workflows/test.yml
  README.md
  src/fairchem/demo/ocpapi/README.md
Labels: test, cla signed, no-op

#1428 StrEnum backwards compatibility
  src/fairchem/core/_cli.py
  src/fairchem/core/calculate/ase_calculator.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/units/mlip_unit/api/inference.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
Labels: bug, patch, cla signed

#1368 [ BE ] refactored init edge rot mat
  .github/workflows/test.yml
  src/fairchem/core/models/uma/common/rotation.py
  src/fairchem/core/models/uma/common/rotation_cuda_graph.py
  src/fairchem/core/models/uma/escn_md.py
  tests/core/conftest.py
  tests/core/models/uma/test_rotation_cuda_graph.py
  tests/core/units/mlip_unit/conftest.py
  tests/core/units/mlip_unit/test_mlip_unit.py
Labels: enhancement, minor, cla signed

#1402 Evaluation and benchmark docs
  docs/core/common_tasks/ase_calculator.md
  docs/core/common_tasks/ase_dataset_creation.md
  docs/core/common_tasks/benchmark.md
  docs/core/common_tasks/evaluation.md
  docs/core/common_tasks/training.md
  docs/core/common_tasks/workflows.md
Labels: documentation, cla signed, no-op

#1415 Inference server + client for running local MP graph parallel
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/calculate/ase_calculator.py
  src/fairchem/core/common/distutils.py
  src/fairchem/core/datasets/common_structures.py
  src/fairchem/core/models/uma/common/rotation_cuda_graph.py
  src/fairchem/core/units/mlip_unit/inference/client_server_example.py
  src/fairchem/core/units/mlip_unit/inference/client_websocket.py
  src/fairchem/core/units/mlip_unit/inference/inference_server_ray.py
  src/fairchem/core/units/mlip_unit/inference/server_config.yaml
  src/fairchem/core/units/mlip_unit/predict.py
  tests/core/calculate/test_ase_calculator.py
  tests/core/units/mlip_unit/test_predict.py
Labels: enhancement, minor, cla signed

#1443 Add release workflows for fairchem-data-omol
  .github/workflows/build.yml
  .github/workflows/release-drafter-data-omol.yml
  .github/workflows/release-drafter-data_omol.yml
  .github/workflows/release.yml
  .github/workflows/test-release.yml
  packages/fairchem-data-omol/pyproject.toml
Labels: enhancement, github_actions, cla signed, no-op

#1433 Inference performance test convergence
  .github/workflows/perf-test.yml
  tests/perf/performance_report.py
  tests/perf/test_inference.py
Labels: test, patch, cla signed

#1442 Fix ODAC Docs
  docs/_toc.yml
Labels: documentation, patch, cla signed

#1412 Add OMol evaluations
  configs/uma/benchmark/omol-geom.yaml
  configs/uma/benchmark/omol-ieea.yaml
  configs/uma/benchmark/omol-pocket.yaml
  configs/uma/benchmark/omol-prot.yaml
  configs/uma/benchmark/omol-scale.yaml
  configs/uma/benchmark/omol-spin.yaml
  configs/uma/benchmark/omol-strain.yaml
  docs/molecules/leaderboard.md
  src/fairchem/core/components/benchmark/benchmark_reducer.py
  src/fairchem/core/components/benchmark/omol_reducer.py
  src/fairchem/core/components/calculate/omol_runner.py
  src/fairchem/core/components/calculate/recipes/omol.py
  tests/core/components/test_omol_recipes.py
Labels: enhancement, minor, cla signed

#1447 fix docs, reset calc
  configs/uma/benchmark/omol-scale.yaml
  docs/_toc.yml
  docs/molecules/leaderboard.md
  src/fairchem/core/components/calculate/recipes/omol.py
Labels: documentation, cla signed, no-op

#1450 add merge_group triggers
  .github/workflows/build_docs.yml
  .github/workflows/test.yml
Labels: test, cla signed, no-op

#1418 Update lmdb version to 1.7.3
  packages/fairchem-core/pyproject.toml
  tests/requirements.txt
Labels: dependencies, patch, cla signed
