Repository facebookresearch/fairchem, pull requests merged in 2025-09, with the labels that each got.

#1454 Lammps Integration v0
  .github/workflows/test.yml
  docs/core/common_tasks/ase_calculator.md
  docs/core/common_tasks/lammps.md
  packages/fairchem-lammps/pyproject.toml
  packages/fairchem-lammps/src
  src/fairchem/core/units/mlip_unit/inference/client_websocket.py
  src/fairchem/core/units/mlip_unit/inference/server_config.yaml
  src/fairchem/lammps/LICENSE.md
  src/fairchem/lammps/README.md
  src/fairchem/lammps/__init__.py
  src/fairchem/lammps/lammps_fc.py
  src/fairchem/lammps/lammps_fc_config.yaml
  src/fairchem/lammps/lammps_in_example.file
  tests/core/scripts/test_create_finetune_dataset.py
  tests/lammps/lammps_langevin.file
  tests/lammps/lammps_nve.file
  tests/lammps/test_ase_vs_lammps.py
Labels: enhancement, minor, cla signed

#1495 Fix fairchem-lammps build and docs
  .github/workflows/build.yml
  docs/core/common_tasks/lammps.md
Labels: enhancement, minor, cla signed

#1327 Add EScAIP Model
  configs/escaip/benchmark/checkpoint/escaip_tot_sm.yaml
  configs/escaip/benchmark/cluster/fair_cluster.yaml
  configs/escaip/benchmark/cluster/fair_local.yaml
  configs/escaip/benchmark/oc20-s2ef-id.yaml
  configs/escaip/benchmark/oc20-s2ef-ood-both.yaml
  configs/escaip/training/backbone/H1024L8.yaml
  configs/escaip/training/backbone/H512L10.yaml
  configs/escaip/training/backbone/H640L10.yaml
  configs/escaip/training/cluster/fair_cluster.yaml
  configs/escaip/training/cluster/fair_local.yaml
  configs/escaip/training/dataset/fair_cluster_mptrj.yaml
  configs/escaip/training/dataset/fair_cluster_oc20.yaml
  configs/escaip/training/dataset/fair_cluster_spice.yaml
  configs/escaip/training/element_refs/mptrj_lin_refs.yaml
  configs/escaip/training/element_refs/spice_lin_refs.yaml
  configs/escaip/training/element_refs/uma_v1_hof_lin_refs.yaml
  configs/escaip/training/mptrj_direct_escaip_fair.yml
  configs/escaip/training/mptrj_finetune_escaip_fair.yml
  configs/escaip/training/oc20_direct_escaip_fair.yml
  configs/escaip/training/oc20_direct_escaip_fair_sm.yml
  configs/escaip/training/spice_grad_escaip_fair.yml
  configs/escaip/training/tasks/mptrj_direct.yaml
  configs/escaip/training/tasks/mptrj_grad.yaml
  configs/escaip/training/tasks/oc20_direct.yaml
  configs/escaip/training/tasks/spice_direct.yaml
  configs/escaip/training/tasks/spice_grad.yaml
  src/fairchem/core/models/escaip/EScAIP.py
  src/fairchem/core/models/escaip/__init__.py
  src/fairchem/core/models/escaip/configs.py
  src/fairchem/core/models/escaip/custom_types.py
  src/fairchem/core/models/escaip/modules/__init__.py
  src/fairchem/core/models/escaip/modules/base_block.py
  src/fairchem/core/models/escaip/modules/graph_attention_block.py
  src/fairchem/core/models/escaip/modules/input_block.py
  src/fairchem/core/models/escaip/modules/output_block.py
  src/fairchem/core/models/escaip/modules/readout_block.py
  src/fairchem/core/models/escaip/utils/data_preprocess.py
  src/fairchem/core/models/escaip/utils/graph_utils.py
  src/fairchem/core/models/escaip/utils/nn_utils.py
  src/fairchem/core/models/escaip/utils/radius_graph.py
  src/fairchem/core/models/escaip/utils/smearing.py
  src/fairchem/core/models/escaip/utils/stochastic_depth.py
  src/fairchem/core/units/mlip_unit/mlip_unit.py
  src/fairchem/core/units/mlip_unit/utils.py
  tests/core/models/escaip/fixed_results.pt
  tests/core/models/escaip/test_forward.py
Labels: enhancement, minor, cla signed

#1505 upgrade clusterscope
  packages/fairchem-core/pyproject.toml
Labels: dependencies, minor, cla signed

#1518 add to toc
  docs/_toc.yml
  docs/molecules/datasets/omol25_elec.md
Labels: documentation, patch, cla signed

#1517 Add warning for formation energy calculations using OMat24
  README.md
Labels: documentation, cla signed, no-op

#1523 remove wigner_cuda / cuda_graph
  configs/uma/benchmark/uma-speed.yaml
  docs/core/common_tasks/ase_calculator.md
  src/fairchem/core/models/uma/escn_md.py
  src/fairchem/core/units/mlip_unit/api/inference.py
  src/fairchem/core/units/mlip_unit/inference/client_server_example.py
  src/fairchem/core/units/mlip_unit/inference/server_config.yaml
  src/fairchem/core/units/mlip_unit/predict.py
  src/fairchem/lammps/lammps_fc_config.yaml
  tests/core/calculate/test_ase_calculator.py
  tests/core/units/mlip_unit/test_inference_checkpoint.py
  tests/core/units/mlip_unit/test_inference_modes.py
  tests/core/units/mlip_unit/test_predict.py
Labels: deprecation, minor, cla signed

#1502 Bump torch 2p8
  configs/uma/benchmark/uma-speed.yaml
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/models/uma/common/rotation.py
  src/fairchem/core/models/uma/escn_md.py
  src/fairchem/core/models/uma/escn_md_block.py
  src/fairchem/core/models/uma/nn/embedding_dev.py
  src/fairchem/core/models/uma/nn/so2_layers.py
  tests/core/models/uma/test_compile.py
  tests/core/units/mlip_unit/test_inference_modes.py
  tests/requirements.txt
Labels: enhancement, patch, cla signed
