Repository facebookresearch/fairchem, pull requests merged in 2025-04, with the labels that each got.

#1096 Fix the original repo name in docs
  docs/index.md
Labels: documentation, patch

#1082 Graph parallel fix and tests
  src/fairchem/core/common/gp_utils.py
  tests/core/common/test_gp_utils.py
  tests/core/e2e/test_s2ef.py
Labels: bug, minor

#1095 initialize distributed process with different ports if world size = 1
  src/fairchem/core/common/distutils.py
Labels: enhancement, patch

#999 Switch to upstream LMDB Database
  .github/workflows/build_docs.yml
  .gitignore
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/requirements.txt
  src/fairchem/core/datasets/__init__.py
  src/fairchem/core/datasets/ase_datasets.py
  src/fairchem/core/datasets/lmdb_database.py
  tests/core/conftest.py
  tests/core/datasets/test_ase_datasets.py
  tests/core/datasets/test_ase_lmdb.py
  tests/core/datasets/test_create_dataset.py
  tests/core/datasets/test_lmdb_dataset.py
Labels: deprecation, dependencies, minor

#1099 ruff ignore RET504
  ruff.toml
Labels: test, patch

#1100 resolve run_dir to abspath
  src/fairchem/core/_cli_hydra.py
Labels: enhancement, patch

#1102 Log test duration, disable ESCN compiles tests
  .github/workflows/test.yml
  tests/core/models/test_escn_compiles.py
Labels: bug, patch

#1091 add check to make sure num_nodes<=1 for local mode
  src/fairchem/core/_cli_hydra.py
Labels: enhancement, patch

#1088 check if submitted_pickle exists before attempting to remove runner_state_path
  src/fairchem/core/_cli_hydra.py
Labels: bug, patch

#1052 remove segment_csr / segment_coo dependency
  src/fairchem/core/common/utils.py
  src/fairchem/core/models/schnet.py
  tests/core/common/test_pyg_replacements.py
  tests/core/preprocessing/test_radius_graph_pbc.py
Labels: enhancement, patch

#1104 Only initialize logger once
  src/fairchem/core/_cli_hydra.py
Labels: bug, patch, cla signed

#1103 afterok all run job array jobs
  src/fairchem/core/_cli_hydra.py
Labels: bug, patch, cla signed

#1090 eSEN code release
  src/fairchem/core/models/esen/Jd.pt
  src/fairchem/core/models/esen/__init__.py
  src/fairchem/core/models/esen/common/__init__.py
  src/fairchem/core/models/esen/common/rotation.py
  src/fairchem/core/models/esen/common/so3.py
  src/fairchem/core/models/esen/esen.py
  src/fairchem/core/models/esen/esen_block.py
  src/fairchem/core/models/esen/esen_dens.py
  src/fairchem/core/models/esen/nn/__init__.py
  src/fairchem/core/models/esen/nn/activation.py
  src/fairchem/core/models/esen/nn/embedding.py
  src/fairchem/core/models/esen/nn/layer_norm.py
  src/fairchem/core/models/esen/nn/radial.py
  src/fairchem/core/models/esen/nn/rank2.py
  src/fairchem/core/models/esen/nn/so2_layers.py
  src/fairchem/core/models/esen/nn/so3_layers.py
  src/fairchem/core/models/esen/trainers/__init__.py
  src/fairchem/core/models/esen/trainers/lr_scheduler.py
  src/fairchem/core/models/esen/trainers/trainer.py
Labels: enhancement, minor, cla signed

#1115 add eSEN model checkpoints to registry
  src/fairchem/core/models/model_registry.py
  src/fairchem/core/models/pretrained_models.json
Labels: enhancement, minor, cla signed
