Repository facebookresearch/fairchem, pull requests merged in 2025-03, with the labels that each got.

#1044 Add results dir for saving full predictions/metrics
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
Labels: enhancement, patch

#1040 Add disable_amp flag to OCP calculator
  src/fairchem/core/common/relaxation/ase_utils.py
Labels: enhancement, minor

#1047 get hash of both core and experimental
  src/fairchem/core/common/utils.py
Labels: enhancement, patch

#1048 Hf model name download
  .github/workflows/test.yml
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/fairchem-core/pyproject.toml
  packages/requirements.txt
  src/fairchem/core/models/model_registry.py
  src/fairchem/core/models/pretrained_models.json
  src/fairchem/core/models/pretrained_models.yml
  tests/core/common/test_ase_calculator.py
Labels: enhancement, dependencies, minor

#1049 lower huggingfacehub version
  packages/env.cpu.yml
  packages/env.gpu.yml
  packages/fairchem-core/pyproject.toml
  packages/requirements.txt
Labels: dependencies, patch

#1051 Always attempt to load checkpoint
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/components/runner.py
Labels: enhancement, patch

#1009 Enable slurm arrays in new cli
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/components/runner.py
Labels: enhancement, minor

#1056 Fix github codespace install
  .devcontainer/postCreateCommand.sh
Labels: documentation, patch

#1055 Remove runner_state_path from submission pickle
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
  src/fairchem/core/components/runner.py
Labels: enhancement, patch

#1050 Fix typo in model registry names
  src/fairchem/core/models/pretrained_models.json
Labels: enhancement, patch

#1059 only run tests if hf token is present
  tests/core/common/test_ase_calculator.py
Labels: bug, patch

#1061 Move pickle modification into main rank behind barrier
  src/fairchem/core/_cli_hydra.py
Labels: bug, patch

#1043 Adding omitted dependencies to `fairchem-core`'s `pyproject.toml`
  packages/fairchem-core/pyproject.toml
Labels: dependencies, patch

#1060 Minor fixes in tutorial notebook regarding directory naming and one typo
  src/fairchem/applications/AdsorbML/tutorials/adsorbml_walkthrough.ipynb
Labels: bug, documentation, patch

#1058 PR #1057 Download file to proper location when working in PyPi-installed build
  .github/workflows/test.yml
  src/fairchem/core/scripts/download_large_files.py
  tests/applications/cattsunami/tests/conftest.py
Labels: bug, patch

#1076 wandb log pandas dataframes
  src/fairchem/core/common/logger.py
Labels: enhancement, minor

#1067 Add fix gp grad
  src/fairchem/core/common/gp_utils.py
Labels: enhancement, patch

#1077 more config fixes
  configs/oc20/is2re/100k/dimenet_plus_plus/dpp.yml
  configs/oc20/is2re/100k/schnet/schnet.yml
  configs/oc20/is2re/10k/dimenet_plus_plus/dpp.yml
  configs/oc20/is2re/10k/schnet/schnet.yml
  configs/oc20/is2re/all/dimenet_plus_plus/dpp.yml
  configs/oc20/is2re/all/painn/painn_h1024_bs8x4.yml
  configs/oc20/is2re/all/schnet/schnet.yml
  configs/oc20/s2ef/200k/dimenet_plus_plus/dpp.yml
  configs/oc20/s2ef/200k/gemnet/gemnet-dT.yml
  configs/oc20/s2ef/200k/gemnet/gemnet-oc.yml
  configs/oc20/s2ef/200k/schnet/schnet.yml
  configs/oc20/s2ef/20M/dimenet_plus_plus/dpp.yml
  configs/oc20/s2ef/20M/gemnet/gemnet-dT.yml
  configs/oc20/s2ef/20M/gemnet/gemnet-oc.yml
  configs/oc20/s2ef/20M/schnet/schnet.yml
  configs/oc20/s2ef/2M/dimenet_plus_plus/dpp.yml
  configs/oc20/s2ef/2M/equiformer_v2/equiformer_v2_N@12_L@6_M@2.yml
  configs/oc20/s2ef/2M/escn/eSCN-L4-M2-Lay12.yml
  configs/oc20/s2ef/2M/escn/eSCN-L6-M2-Lay12.yml
  configs/oc20/s2ef/2M/gemnet/gemnet-dT.yml
  configs/oc20/s2ef/2M/gemnet/gemnet-oc.yml
  configs/oc20/s2ef/2M/schnet/schnet.yml
  configs/oc20/s2ef/2M/scn/scn-t1-b1.yml
  configs/oc20/s2ef/2M/scn/scn-t4-b2.yml
  configs/oc20/s2ef/all/dimenet_plus_plus/dpp.yml
  configs/oc20/s2ef/all/escn/eSCN-L6-M2-Lay12-All-MD.yml
  configs/oc20/s2ef/all/escn/eSCN-L6-M3-Lay20-All-MD.yml
  configs/oc20/s2ef/all/gemnet/gemnet-dT.yml
  configs/oc20/s2ef/all/gemnet/gemnet-oc-large.yml
  configs/oc20/s2ef/all/gemnet/gemnet-oc.yml
  configs/oc20/s2ef/all/gp_gemnet/gp-gemnet-dT.yml
  configs/oc20/s2ef/all/gp_gemnet/gp-gemnet-xl.yml
  configs/oc20/s2ef/all/painn/painn_h512.yml
  configs/oc20/s2ef/all/schnet/schnet.yml
  configs/oc20/s2ef/all/scn/scn-all-md.yml
  docs/core/model_checkpoints.md
  docs/core/model_faq.md
  docs/core/model_training.md
  docs/legacy_tutorials/OCP_Tutorial.md
Labels: bug, patch

#1074 Fix tensorboard logger
  src/fairchem/core/trainers/base_trainer.py
Labels: bug, patch

#1064 support for direct slab inputs
  src/fairchem/data/oc/core/slab.py
  tests/data/oc/tests/test_adsorbate_slab_config.py
Labels: enhancement, patch

#1069 Reducer
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/logger.py
  src/fairchem/core/components/reducer.py
  src/fairchem/core/components/runner.py
  tests/core/test_hydra_cli.py
  tests/core/test_hydra_cli_run_reduce.yml
Labels: enhancement, minor

#1075 gemnet-oc molecules support
  src/fairchem/core/models/gemnet_oc/gemnet_oc.py
  src/fairchem/core/models/gemnet_oc/layers/efficient.py
  src/fairchem/core/models/gemnet_oc/layers/spherical_basis.py
  tests/core/models/test_gemnet_oc_molecules.py
Labels: enhancement, patch

#1080 add split info to metadata
  docs/core/datasets/oc20.md
Labels: documentation, enhancement, patch

#1070 Add documentation for using quacc with OMat models and huggingface
  .github/workflows/build_docs.yml
  .gitignore
  docs/.quacc.yml
  docs/_toc.yml
  docs/core/inorganic_materials.md
  docs/core/license.md
  packages/fairchem-core/pyproject.toml
Labels: documentation, enhancement, minor

#1084 fix doc deployment
  .github/workflows/deploy_docs.yml
  packages/fairchem-core/pyproject.toml
Labels: bug, documentation, github_actions, patch

#1083 Config descriptors
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/components/reducer.py
  src/fairchem/core/components/runner.py
  src/fairchem/core/components/utils.py
Labels: enhancement, minor

#1089 always set r_edges to False in OCPCalculator
  src/fairchem/core/common/relaxation/ase_utils.py
Labels: bug, patch
