Repository facebookresearch/fairchem, pull requests merged in 2025-01, with the labels that each got.

#951 Update env.cpu.yml
  packages/env.cpu.yml
Labels: dependencies, minor, patch

#963 fix train dataset links and correct val links and sizes
  docs/core/datasets/omat24.md
Labels: documentation, patch

#967 Install hydra and torchtnt
  packages/env.gpu.yml
  src/fairchem/core/common/utils.py
Labels: dependencies, minor

#971 fix link typo
  docs/core/datasets/omat24.md
Labels: documentation, patch

#930 Fix Deprecation Warnings torch.GradScaler and torch.autocast
  docs/tutorials/advanced/embedding_monkeypatch.py
  src/fairchem/core/models/equiformer_v2/equiformer_v2_deprecated.py
  src/fairchem/core/models/equiformer_v2/layer_norm.py
  src/fairchem/core/models/equiformer_v2/trainers/dens_trainer.py
  src/fairchem/core/models/gemnet_oc/gemnet_oc.py
  src/fairchem/core/models/gemnet_oc/layers/force_scaler.py
  src/fairchem/core/modules/scaling/fit.py
  src/fairchem/core/trainers/base_trainer.py
  src/fairchem/core/trainers/ocp_trainer.py
Labels: enhancement, patch

#965 Misc ASE db bugfixes
  src/fairchem/core/common/tutorial_utils.py
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  tests/core/preprocessing/test_atoms_to_graphs.py
Labels: bug, patch

#977 Add git hash changes announcement
  GIT-CHANGES-17-01-25.md
  README.md
Labels: documentation, patch

#976 Add structured configs to hydra cli, pass cfg to runners
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/_cli.py
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/flags.py
  src/fairchem/core/components/runner.py
  tests/core/test_hydra_cli.py
  tests/core/test_hydra_cli.yml
Labels: enhancement, minor
