Repository facebookresearch/fairchem, pull requests merged in 2025-02, with the labels that each got.

#991 Add cosine LR, minor edit to hydra cli
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/modules/scheduler.py
  tests/core/test_hydra_cli.py
Labels: enhancement, patch

#993 change order of key mapping transform
  src/fairchem/core/datasets/ase_datasets.py
  src/fairchem/core/datasets/lmdb_dataset.py
  src/fairchem/core/datasets/oc22_lmdb_dataset.py
Labels: enhancement, patch

#996 Strictly enforce no unused keys in yaml
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/components/runner.py
  tests/core/test_hydra_cli.py
  tests/core/test_hydra_cli.yml
Labels: enhancement, minor

#998 astroid<4
  packages/fairchem-core/pyproject.toml
Labels: bug, dependencies, minor

#985 Allow dataset subset to read in path to rhv
  src/fairchem/core/datasets/base_dataset.py
  tests/core/datasets/test_create_dataset.py
Labels: enhancement, patch

#995 Fix OCPNeb trainer loading
  src/fairchem/applications/cattsunami/core/ocpneb.py
Labels: bug, minor

#1002 Add seeds and deterministic mode to Hydra cli
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
  tests/core/common/test_utils_.py
Labels: enhancement, minor

#1005 update reduction to mean in omat24 configs
  configs/omat24/all/eqV2_153M.yml
  configs/omat24/all/eqV2_31M.yml
  configs/omat24/all/eqV2_86M.yml
  configs/omat24/finetune/eqV2_153M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_31M_ft_salexmptrj.yml
  configs/omat24/finetune/eqV2_86M_ft_salexmptrj.yml
  configs/omat24/mptrj/eqV2_153M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_dens_mptrj.yml
  configs/omat24/mptrj/eqV2_31M_mptrj.yml
  configs/omat24/mptrj/eqV2_86M_dens_mptrj.yml
Labels: documentation, minor

#1006 Make slurm config separate class
  packages/fairchem-core/pyproject.toml
  src/fairchem/core/_cli_hydra.py
Labels: enhancement, dependencies, patch

#1008 Modify runner and cli for state checkpointing
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/components/runner.py
Labels: enhancement, minor

#1013 OCPNeb fix for finetuned + new trained models
  src/fairchem/applications/cattsunami/core/ocpneb.py
Labels: bug, patch

#1014 Remove use of device from bbsampler
  src/fairchem/core/common/data_parallel.py
  src/fairchem/core/common/distutils.py
Labels: enhancement, minor

#1016 Fix preemption behavior and combine config init
  src/fairchem/core/_cli_hydra.py
  tests/core/test_hydra_cli.py
Labels: bug, enhancement, minor

#1020 Add profiler callback
  src/fairchem/core/common/profiler_utils.py
Labels: enhancement, minor

#1019 Add molecule cell to a2g
  src/fairchem/core/preprocessing/atoms_to_graphs.py
  tests/core/preprocessing/test_atoms_to_graphs.py
Labels: enhancement, minor

#1023 move two operations to out of place
  src/fairchem/core/common/gp_utils.py
Labels: enhancement, patch

#997 add backbone override to hydra
  src/fairchem/core/models/base.py
  tests/core/e2e/test_e2e_finetune_hydra.py
Labels: enhancement, patch

#1030 add nedges to atoms2graph
  src/fairchem/core/preprocessing/atoms_to_graphs.py
Labels: enhancement, patch

#1034 [cli_hydra] Add cluster name to metadata
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/utils.py
Labels: enhancement, minor

#1032 add graph parallel initialization
  src/fairchem/core/_cli_hydra.py
  src/fairchem/core/common/gp_utils.py
Labels: enhancement, patch

#1035 Update pyproject to match torch 2.4.x patch versions
  packages/fairchem-core/pyproject.toml
Labels: bug, dependencies

#1037 sort fix for multiple src
  src/fairchem/core/datasets/ase_datasets.py
Labels: bug, patch

#1038 add error when submitting job from srun/slurm
  src/fairchem/core/_cli_hydra.py
Labels: enhancement, patch
